spring:
  application:
    name: ca-reservation
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db.url:jdbc:mysql://localhost:3306/sharingtest}
    username: ${db.username:root}
    password: ${db.password:1234}
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
  jpa:
    hibernate:
      ddl-auto: ${db.ddl:create}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      jakarta:
        persistence:
          validation:
            mode: none
    show-sql: false


kafka:
  url: 127.0.0.1:29092

server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

product:
  client:
    url: https://localhost:8000/ca-product