#### 예약 가입
#POST {{reservation-api}}/ca-reservation/create
POST http://192.168.1.103:8000/ca-reservation/create
Content-Type: application/json

{
 "guestId" : "UUID123456",
  "productId": "1"
}

#### 테스트
GET http://192.168.1.103:8000/ca-reservation/test
#GET {{home-address}}:8080/ca-reservation/test